// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config } from "dotenv";

// Load .env.local first (same order as seed) so migrate/deploy and seed use the same DATABASE_URL
const root = path.resolve(process.cwd());
config({ path: path.join(root, ".env.local") });
config({ path: path.join(root, ".env") });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
