-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFaMethod" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otpCodeHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otpExpiresAt" TIMESTAMP(3);
