/**
 * Marketing Channel Configuration
 * Centralized toggles and IDs for all marketing integrations.
 */

export const MARKETING_CONFIG = {
  // META (Facebook/Instagram)
  META_PIXEL_ENABLED: process.env.NEXT_PUBLIC_META_PIXEL_ENABLED === 'true' || true, // Always enabled in production
  META_PIXEL_ID: process.env.NEXT_PUBLIC_META_PIXEL_ID ?? '2035196960739715',
  META_CONVERSIONS_API_ENABLED: process.env.META_CONVERSIONS_API_ENABLED === 'true',
  META_ACCESS_TOKEN: process.env.META_ACCESS_TOKEN,

  // GOOGLE (ADS/GA4/GTM)
  GTM_ENABLED: process.env.NEXT_PUBLIC_GTM_ENABLED === 'true' || true, // Always enabled in production
  GTM_ID: process.env.NEXT_PUBLIC_GTM_ID ?? 'GTM-K5G6H3HP',
  GA4_ID: process.env.NEXT_PUBLIC_GA4_ID,
  GOOGLE_ADS_ID: process.env.NEXT_PUBLIC_GOOGLE_ADS_ID,
  GOOGLE_MERCHANT_ID: process.env.NEXT_PUBLIC_GOOGLE_MERCHANT_ID,

  // TIKTOK
  TIKTOK_PIXEL_ENABLED: process.env.NEXT_PUBLIC_TIKTOK_PIXEL_ENABLED === 'true',
  TIKTOK_PIXEL_ID: process.env.NEXT_PUBLIC_TIKTOK_PIXEL_ID,
  TIKTOK_EVENTS_API_TOKEN: process.env.TIKTOK_EVENTS_API_TOKEN,

  // X (TWITTER)
  X_PIXEL_ENABLED: process.env.NEXT_PUBLIC_X_PIXEL_ENABLED === 'true',
  X_PIXEL_ID: process.env.NEXT_PUBLIC_X_PIXEL_ID,

  // SNAPCHAT
  SNAP_PIXEL_ENABLED: process.env.NEXT_PUBLIC_SNAP_PIXEL_ENABLED === 'true',
  SNAP_PIXEL_ID: process.env.NEXT_PUBLIC_SNAP_PIXEL_ID,
  SNAP_CONVERSIONS_API_TOKEN: process.env.SNAP_CONVERSIONS_API_TOKEN,

  // PINTEREST
  PINTEREST_TAG_ENABLED: process.env.NEXT_PUBLIC_PINTEREST_TAG_ENABLED === 'true',
  PINTEREST_TAG_ID: process.env.NEXT_PUBLIC_PINTEREST_TAG_ID,
  PINTEREST_ACCESS_TOKEN: process.env.PINTEREST_ACCESS_TOKEN,
  PINTEREST_AD_ACCOUNT_ID: process.env.PINTEREST_AD_ACCOUNT_ID,

  // KLAVIYO
  KLAVIYO_ENABLED: process.env.KLAVIYO_ENABLED === 'true',
  KLAVIYO_API_KEY: process.env.KLAVIYO_API_KEY,
  KLAVIYO_PUBLIC_KEY: process.env.NEXT_PUBLIC_KLAVIYO_PUBLIC_KEY,

  // WHATSAPP BUSINESS
  WHATSAPP_ENABLED: process.env.WHATSAPP_ENABLED === 'true',
  WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
  WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,

  // TWILIO (for fallback or specific SMS/WhatsApp)
  TWILIO_SID: process.env.TWILIO_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
};
